export class DocumentosModel {
    id: string;
    cNombreDocumento: string;
    bActivo: boolean;
    fechaCreacion: any;
    fechaCarga: any;
    paginas: number;
    tipo_de_documento: any;
    version: number;
    documento: any;
    ente: any;
    // secretaria: any;
    // departamento: any;
    // direccion: any;
    folioExpediente: any;
    metacatalogos: any;
    disabled: boolean;
    Eliminar: boolean;
    visibilidade: any;
    tipo_de_expediente: any;
    usuario: any;
    textoOcr: string;
    iniciativas: boolean;
    legislatura: any;
    iniciativa: any;
    estatus:string;
    formulario: string;
    iniciativaOficioEnvioDeInforme: any;
    iniciativaInformeDeResultadosRevision: any;
    ordenDelDia: any;
    listaDeAsistencia: any;
    actasSesion: any;
    numeroPagina: number;
    plazoDeConservacion: number;
    clave: string;
}
